# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ingest_pb2 as ingest__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ingest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestServiceStub:
    """IngestService is the device-facing data-plane API.
    Auth: the device sends "authorization: Bearer <device-token>" in gRPC metadata.
    The server derives device_id from the token; it is intentionally absent from
    every message so a device cannot spoof another device's id.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_unary(
                '/iot.ingest.v1.IngestService/Stream',
                request_serializer=ingest__pb2.Reading.SerializeToString,
                response_deserializer=ingest__pb2.StreamSummary.FromString,
                _registered_method=True)


class IngestServiceServicer:
    """IngestService is the device-facing data-plane API.
    Auth: the device sends "authorization: Bearer <device-token>" in gRPC metadata.
    The server derives device_id from the token; it is intentionally absent from
    every message so a device cannot spoof another device's id.
    """

    def Stream(self, request_iterator, context):
        """Stream is client-streaming: the device opens it once and pushes readings
        continuously. The server returns a summary when the client half-closes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_unary_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=ingest__pb2.Reading.FromString,
                    response_serializer=ingest__pb2.StreamSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iot.ingest.v1.IngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iot.ingest.v1.IngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestService:
    """IngestService is the device-facing data-plane API.
    Auth: the device sends "authorization: Bearer <device-token>" in gRPC metadata.
    The server derives device_id from the token; it is intentionally absent from
    every message so a device cannot spoof another device's id.
    """

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/iot.ingest.v1.IngestService/Stream',
            ingest__pb2.Reading.SerializeToString,
            ingest__pb2.StreamSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
